schema_version = "1.0.0"
id = "sunders_video_editing"
version = "1.0.0"
name = "Sunders Video Editing"
tagline = "This is another extension"
maintainer = "SunderCode <sundercasting@gmail.com>"
type = "add-on"
tags = ["Animation", "Sequencer"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later",
]

[permissions]
files = "Creates empty proxy images in temp folder"
